name: Job Checker

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:       # allows manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          SENDER: ${{ secrets.SENDER }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          RECEIVER: ${{ secrets.RECEIVER }}
        run: python main.py

      - name: Commit updated CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add old_jobs.csv
          git commit -m "Update jobs file" || echo "No changes"
          git push
